// Modal synthesis graph for object 'ceramic_plate'.
//
// Auto-generated by scripts/modal/codegen/crag_emitter.py from a
// ModeTable produced by the offline FEM extraction pipeline.
// 43 mode(s); sample rate 48000 Hz.
//
// Per-mode IIR design parameters (cutoff, Q) are baked at codegen
// time so the runtime graph has zero per-sample parameter lookups
// inside the resonator inner loop.  The actual
// 2-pole IIR body is built inline by the
// `crag.get_filter_coeffs type = "two_pole_resonator"` lowering.

module {
  crag.graph sample_rate = 48000 channels = 1 {

    // ── Parameters ────────────────────────────────────────────────────────
    %output_gain       = crag.param "output_gain" min = 0.0 max = 4.0 default = 1.0 : f32
    %dampen            = crag.param "dampen" min = 0.0 max = 1.0 default = 0.0 : f32
    %drag_velocity     = crag.param "drag_velocity" min = 0.0 max = 1.0 default = 0.0 : f32
    %drag_roughness    = crag.param "drag_roughness" min = 0.0 max = 1.0 default = 0.5 : f32
    %drag_normal_force = crag.param "drag_normal_force" min = 0.0 max = 1.0 default = 0.5 : f32
    %contact_u         = crag.param "contact_u" min = 0.0 max = 1.0 default = 0.5 : f32
    %contact_v         = crag.param "contact_v" min = 0.0 max = 1.0 default = 0.5 : f32
    %impulse_velocity  = crag.param "impulse_velocity" min = 0.0 max = 1.0 default = 0.5 : f32
    %impulse_angle     = crag.param "impulse_angle" min = 0.0 max = 1.5707963 default = 0.0 unit = "rad" : f32
    %damping_override  = crag.param "damping_override" min = 0.0 max = 1.0 default = 0.0 : f32
    %pitch_shift       = crag.param "pitch_shift" min = 0.5 max = 2.0 default = 1.0 : f32

    // ── Events ────────────────────────────────────────────────────────────
    %impulse_fired, %impulse_at = crag.event_void "impulse" : i1, i32
    %drag_start_fired, %drag_start_at = crag.event_void "drag_start" : i1, i32
    %drag_stop_fired,  %drag_stop_at  = crag.event_void "drag_stop"  : i1, i32

    // ── Impulse excitation: ADSR hammer-hit on `impulse` event ───────────
    %imp_attack_ms = arith.constant 0.1 : f32
    %imp_decay_ms  = arith.constant 1.0 : f32
    %imp_sustain   = arith.constant 0.0 : f32
    %imp_release   = arith.constant 0.0 : f32
    %imp_env = crag.adsr %imp_attack_ms, %imp_decay_ms, %imp_sustain, %imp_release, %impulse_fired, %impulse_at : f32, f32, f32, f32, i1, i32 -> !crag.audio<f32, 48000, 1>
    %impulse_exc = crag.scale %imp_env, %impulse_velocity : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>

    // ── Drag excitation: gated colored noise ────────────────────────────
    %drag_gate_i1 = crag.latch %drag_start_fired, %drag_stop_fired : i1, i1 -> i1
    %drag_gate_f32 = arith.uitofp %drag_gate_i1 : i1 to f32
    %drag_noise = crag.white_noise : !crag.audio<f32, 48000, 1>
    %drag_cutoff = arith.constant 0.125 : f32
    %drag_fb, %drag_ff = crag.get_filter_coeffs %drag_cutoff order = 2 q = 0.9 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %drag_colored = crag.filter %drag_noise, %drag_fb, %drag_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %drag_vel_force = arith.mulf %drag_velocity, %drag_normal_force : f32
    %drag_gain = arith.mulf %drag_vel_force, %drag_gate_f32 : f32
    %drag_exc = crag.scale %drag_colored, %drag_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>

    // ── Excitation mix: impulse + drag → resonator bank input ────────────
    %excitation = crag.sum %impulse_exc, %drag_exc : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>

    // ── Resonator bank (one IIR per surviving mode) ──────────────────────
    %m0_cutoff = arith.constant 0.0534838167 : f32
    %m0_gain   = arith.constant 0.991723524 : f32
    %m0_fb, %m0_ff = crag.get_filter_coeffs %m0_cutoff order = 2 q = 537.341524 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m0_raw = crag.filter %excitation, %m0_fb, %m0_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_0_out = crag.scale %m0_raw, %m0_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m1_cutoff = arith.constant 0.0868981874 : f32
    %m1_gain   = arith.constant 0.0400267429 : f32
    %m1_fb, %m1_ff = crag.get_filter_coeffs %m1_cutoff order = 2 q = 360.566505 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m1_raw = crag.filter %excitation, %m1_fb, %m1_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_1_out = crag.scale %m1_raw, %m1_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m2_cutoff = arith.constant 0.0971645926 : f32
    %m2_gain   = arith.constant 1.66748801 : f32
    %m2_fb, %m2_ff = crag.get_filter_coeffs %m2_cutoff order = 2 q = 326.060605 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m2_raw = crag.filter %excitation, %m2_fb, %m2_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_2_out = crag.scale %m2_raw, %m2_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m3_cutoff = arith.constant 0.120863492 : f32
    %m3_gain   = arith.constant 0.24427234 : f32
    %m3_fb, %m3_ff = crag.get_filter_coeffs %m3_cutoff order = 2 q = 266.319266 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m3_raw = crag.filter %excitation, %m3_fb, %m3_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_3_out = crag.scale %m3_raw, %m3_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m4_cutoff = arith.constant 0.170561727 : f32
    %m4_gain   = arith.constant 0.029878939 : f32
    %m4_fb, %m4_ff = crag.get_filter_coeffs %m4_cutoff order = 2 q = 191.505554 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m4_raw = crag.filter %excitation, %m4_fb, %m4_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_4_out = crag.scale %m4_raw, %m4_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m5_cutoff = arith.constant 0.222849252 : f32
    %m5_gain   = arith.constant 1.76124489 : f32
    %m5_fb, %m5_ff = crag.get_filter_coeffs %m5_cutoff order = 2 q = 147.481961 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m5_raw = crag.filter %excitation, %m5_fb, %m5_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_5_out = crag.scale %m5_raw, %m5_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m6_cutoff = arith.constant 0.240399367 : f32
    %m6_gain   = arith.constant 0.219914346 : f32
    %m6_fb, %m6_ff = crag.get_filter_coeffs %m6_cutoff order = 2 q = 136.884211 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m6_raw = crag.filter %excitation, %m6_fb, %m6_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_6_out = crag.scale %m6_raw, %m6_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m7_cutoff = arith.constant 0.248990658 : f32
    %m7_gain   = arith.constant 0.396811832 : f32
    %m7_fb, %m7_ff = crag.get_filter_coeffs %m7_cutoff order = 2 q = 132.228816 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m7_raw = crag.filter %excitation, %m7_fb, %m7_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_7_out = crag.scale %m7_raw, %m7_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m8_cutoff = arith.constant 0.289586823 : f32
    %m8_gain   = arith.constant 0.0462046426 : f32
    %m8_fb, %m8_ff = crag.get_filter_coeffs %m8_cutoff order = 2 q = 113.901284 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m8_raw = crag.filter %excitation, %m8_fb, %m8_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_8_out = crag.scale %m8_raw, %m8_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m9_cutoff = arith.constant 0.34791602 : f32
    %m9_gain   = arith.constant 0.817320251 : f32
    %m9_fb, %m9_ff = crag.get_filter_coeffs %m9_cutoff order = 2 q = 94.9575546 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m9_raw = crag.filter %excitation, %m9_fb, %m9_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_9_out = crag.scale %m9_raw, %m9_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m10_cutoff = arith.constant 0.35857338 : f32
    %m10_gain   = arith.constant 0.610599936 : f32
    %m10_fb, %m10_ff = crag.get_filter_coeffs %m10_cutoff order = 2 q = 92.1548031 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m10_raw = crag.filter %excitation, %m10_fb, %m10_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_10_out = crag.scale %m10_raw, %m10_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m11_cutoff = arith.constant 0.362363692 : f32
    %m11_gain   = arith.constant 0.136267824 : f32
    %m11_fb, %m11_ff = crag.get_filter_coeffs %m11_cutoff order = 2 q = 91.1973359 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m11_raw = crag.filter %excitation, %m11_fb, %m11_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_11_out = crag.scale %m11_raw, %m11_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m12_cutoff = arith.constant 0.380284613 : f32
    %m12_gain   = arith.constant 1.06155973 : f32
    %m12_fb, %m12_ff = crag.get_filter_coeffs %m12_cutoff order = 2 q = 86.9263619 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m12_raw = crag.filter %excitation, %m12_fb, %m12_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_12_out = crag.scale %m12_raw, %m12_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m13_cutoff = arith.constant 0.382589287 : f32
    %m13_gain   = arith.constant 1.07410081 : f32
    %m13_fb, %m13_ff = crag.get_filter_coeffs %m13_cutoff order = 2 q = 86.4058741 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m13_raw = crag.filter %excitation, %m13_fb, %m13_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_13_out = crag.scale %m13_raw, %m13_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m14_cutoff = arith.constant 0.412040162 : f32
    %m14_gain   = arith.constant 0.145165574 : f32
    %m14_fb, %m14_ff = crag.get_filter_coeffs %m14_cutoff order = 2 q = 80.2630901 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m14_raw = crag.filter %excitation, %m14_fb, %m14_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_14_out = crag.scale %m14_raw, %m14_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m15_cutoff = arith.constant 0.443871548 : f32
    %m15_gain   = arith.constant 0.250724339 : f32
    %m15_fb, %m15_ff = crag.get_filter_coeffs %m15_cutoff order = 2 q = 74.5338065 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m15_raw = crag.filter %excitation, %m15_fb, %m15_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_15_out = crag.scale %m15_raw, %m15_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m16_cutoff = arith.constant 0.463438489 : f32
    %m16_gain   = arith.constant 1.5757149 : f32
    %m16_fb, %m16_ff = crag.get_filter_coeffs %m16_cutoff order = 2 q = 71.4000419 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m16_raw = crag.filter %excitation, %m16_fb, %m16_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_16_out = crag.scale %m16_raw, %m16_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m17_cutoff = arith.constant 0.470941832 : f32
    %m17_gain   = arith.constant 0.174830779 : f32
    %m17_fb, %m17_ff = crag.get_filter_coeffs %m17_cutoff order = 2 q = 70.2669899 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m17_raw = crag.filter %excitation, %m17_fb, %m17_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_17_out = crag.scale %m17_raw, %m17_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m18_cutoff = arith.constant 0.471070092 : f32
    %m18_gain   = arith.constant 0.121462909 : f32
    %m18_fb, %m18_ff = crag.get_filter_coeffs %m18_cutoff order = 2 q = 70.2479339 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m18_raw = crag.filter %excitation, %m18_fb, %m18_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_18_out = crag.scale %m18_raw, %m18_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m19_cutoff = arith.constant 0.499449484 : f32
    %m19_gain   = arith.constant 0.12634776 : f32
    %m19_fb, %m19_ff = crag.get_filter_coeffs %m19_cutoff order = 2 q = 66.2708238 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m19_raw = crag.filter %excitation, %m19_fb, %m19_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_19_out = crag.scale %m19_raw, %m19_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m20_cutoff = arith.constant 0.520007449 : f32
    %m20_gain   = arith.constant 0.0105885291 : f32
    %m20_fb, %m20_ff = crag.get_filter_coeffs %m20_cutoff order = 2 q = 63.6595571 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m20_raw = crag.filter %excitation, %m20_fb, %m20_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_20_out = crag.scale %m20_raw, %m20_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m21_cutoff = arith.constant 0.531340973 : f32
    %m21_gain   = arith.constant 2.89469976 : f32
    %m21_fb, %m21_ff = crag.get_filter_coeffs %m21_cutoff order = 2 q = 62.3059659 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m21_raw = crag.filter %excitation, %m21_fb, %m21_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_21_out = crag.scale %m21_raw, %m21_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m22_cutoff = arith.constant 0.586127678 : f32
    %m22_gain   = arith.constant 0.360320811 : f32
    %m22_fb, %m22_ff = crag.get_filter_coeffs %m22_cutoff order = 2 q = 56.4977422 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m22_raw = crag.filter %excitation, %m22_fb, %m22_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_22_out = crag.scale %m22_raw, %m22_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m23_cutoff = arith.constant 0.592061333 : f32
    %m23_gain   = arith.constant 0.375318598 : f32
    %m23_fb, %m23_ff = crag.get_filter_coeffs %m23_cutoff order = 2 q = 55.9329464 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m23_raw = crag.filter %excitation, %m23_fb, %m23_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_23_out = crag.scale %m23_raw, %m23_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m24_cutoff = arith.constant 0.599235293 : f32
    %m24_gain   = arith.constant 0.433622789 : f32
    %m24_fb, %m24_ff = crag.get_filter_coeffs %m24_cutoff order = 2 q = 55.2649731 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m24_raw = crag.filter %excitation, %m24_fb, %m24_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_24_out = crag.scale %m24_raw, %m24_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m25_cutoff = arith.constant 0.630807165 : f32
    %m25_gain   = arith.constant 0.235333834 : f32
    %m25_fb, %m25_ff = crag.get_filter_coeffs %m25_cutoff order = 2 q = 52.5052314 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m25_raw = crag.filter %excitation, %m25_fb, %m25_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_25_out = crag.scale %m25_raw, %m25_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m26_cutoff = arith.constant 0.699559226 : f32
    %m26_gain   = arith.constant 0.464018576 : f32
    %m26_fb, %m26_ff = crag.get_filter_coeffs %m26_cutoff order = 2 q = 47.3548343 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m26_raw = crag.filter %excitation, %m26_fb, %m26_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_26_out = crag.scale %m26_raw, %m26_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m27_cutoff = arith.constant 0.701627908 : f32
    %m27_gain   = arith.constant 0.451657976 : f32
    %m27_fb, %m27_ff = crag.get_filter_coeffs %m27_cutoff order = 2 q = 47.2154628 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m27_raw = crag.filter %excitation, %m27_fb, %m27_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_27_out = crag.scale %m27_raw, %m27_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m28_cutoff = arith.constant 0.714239958 : f32
    %m28_gain   = arith.constant 0.948045946 : f32
    %m28_fb, %m28_ff = crag.get_filter_coeffs %m28_cutoff order = 2 q = 46.3831812 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m28_raw = crag.filter %excitation, %m28_fb, %m28_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_28_out = crag.scale %m28_raw, %m28_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m29_cutoff = arith.constant 0.761834382 : f32
    %m29_gain   = arith.constant 0.581622294 : f32
    %m29_fb, %m29_ff = crag.get_filter_coeffs %m29_cutoff order = 2 q = 43.4899978 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m29_raw = crag.filter %excitation, %m29_fb, %m29_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_29_out = crag.scale %m29_raw, %m29_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m30_cutoff = arith.constant 0.784120869 : f32
    %m30_gain   = arith.constant 0.876670123 : f32
    %m30_fb, %m30_ff = crag.get_filter_coeffs %m30_cutoff order = 2 q = 42.2557065 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m30_raw = crag.filter %excitation, %m30_fb, %m30_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_30_out = crag.scale %m30_raw, %m30_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m31_cutoff = arith.constant 0.803773125 : f32
    %m31_gain   = arith.constant 1.9071923 : f32
    %m31_fb, %m31_ff = crag.get_filter_coeffs %m31_cutoff order = 2 q = 41.2239775 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m31_raw = crag.filter %excitation, %m31_fb, %m31_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_31_out = crag.scale %m31_raw, %m31_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m32_cutoff = arith.constant 0.809007198 : f32
    %m32_gain   = arith.constant 0.129463161 : f32
    %m32_fb, %m32_ff = crag.get_filter_coeffs %m32_cutoff order = 2 q = 40.9576281 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m32_raw = crag.filter %excitation, %m32_fb, %m32_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_32_out = crag.scale %m32_raw, %m32_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m33_cutoff = arith.constant 0.819920692 : f32
    %m33_gain   = arith.constant 1.77995643 : f32
    %m33_fb, %m33_ff = crag.get_filter_coeffs %m33_cutoff order = 2 q = 40.4131822 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m33_raw = crag.filter %excitation, %m33_fb, %m33_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_33_out = crag.scale %m33_raw, %m33_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m34_cutoff = arith.constant 0.825852824 : f32
    %m34_gain   = arith.constant 0.311381948 : f32
    %m34_fb, %m34_ff = crag.get_filter_coeffs %m34_cutoff order = 2 q = 40.1232682 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m34_raw = crag.filter %excitation, %m34_fb, %m34_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_34_out = crag.scale %m34_raw, %m34_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m35_cutoff = arith.constant 0.844092595 : f32
    %m35_gain   = arith.constant 0.235169662 : f32
    %m35_fb, %m35_ff = crag.get_filter_coeffs %m35_cutoff order = 2 q = 39.2573367 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m35_raw = crag.filter %excitation, %m35_fb, %m35_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_35_out = crag.scale %m35_raw, %m35_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m36_cutoff = arith.constant 0.85827522 : f32
    %m36_gain   = arith.constant 0.490758923 : f32
    %m36_fb, %m36_ff = crag.get_filter_coeffs %m36_cutoff order = 2 q = 38.6094069 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m36_raw = crag.filter %excitation, %m36_fb, %m36_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_36_out = crag.scale %m36_raw, %m36_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m37_cutoff = arith.constant 0.862457676 : f32
    %m37_gain   = arith.constant 0.253370427 : f32
    %m37_fb, %m37_ff = crag.get_filter_coeffs %m37_cutoff order = 2 q = 38.4223938 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m37_raw = crag.filter %excitation, %m37_fb, %m37_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_37_out = crag.scale %m37_raw, %m37_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m38_cutoff = arith.constant 0.86900393 : f32
    %m38_gain   = arith.constant 2.07627082 : f32
    %m38_fb, %m38_ff = crag.get_filter_coeffs %m38_cutoff order = 2 q = 38.133294 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m38_raw = crag.filter %excitation, %m38_fb, %m38_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_38_out = crag.scale %m38_raw, %m38_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m39_cutoff = arith.constant 0.929095708 : f32
    %m39_gain   = arith.constant 1.18564876 : f32
    %m39_fb, %m39_ff = crag.get_filter_coeffs %m39_cutoff order = 2 q = 35.6695186 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m39_raw = crag.filter %excitation, %m39_fb, %m39_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_39_out = crag.scale %m39_raw, %m39_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m40_cutoff = arith.constant 0.932860647 : f32
    %m40_gain   = arith.constant 1.2718267 : f32
    %m40_fb, %m40_ff = crag.get_filter_coeffs %m40_cutoff order = 2 q = 35.5257054 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m40_raw = crag.filter %excitation, %m40_fb, %m40_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_40_out = crag.scale %m40_raw, %m40_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m41_cutoff = arith.constant 0.943423426 : f32
    %m41_gain   = arith.constant 0.330973517 : f32
    %m41_fb, %m41_ff = crag.get_filter_coeffs %m41_cutoff order = 2 q = 35.1283468 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m41_raw = crag.filter %excitation, %m41_fb, %m41_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_41_out = crag.scale %m41_raw, %m41_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m42_cutoff = arith.constant 0.943595184 : f32
    %m42_gain   = arith.constant 1.17149357 : f32
    %m42_fb, %m42_ff = crag.get_filter_coeffs %m42_cutoff order = 2 q = 35.1219589 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m42_raw = crag.filter %excitation, %m42_fb, %m42_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_42_out = crag.scale %m42_raw, %m42_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>

    // ── Sum the bank ─────────────────────────────────────────────────────
    %sum_1 = crag.sum %mode_0_out, %mode_1_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_2 = crag.sum %sum_1, %mode_2_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_3 = crag.sum %sum_2, %mode_3_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_4 = crag.sum %sum_3, %mode_4_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_5 = crag.sum %sum_4, %mode_5_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_6 = crag.sum %sum_5, %mode_6_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_7 = crag.sum %sum_6, %mode_7_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_8 = crag.sum %sum_7, %mode_8_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_9 = crag.sum %sum_8, %mode_9_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_10 = crag.sum %sum_9, %mode_10_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_11 = crag.sum %sum_10, %mode_11_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_12 = crag.sum %sum_11, %mode_12_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_13 = crag.sum %sum_12, %mode_13_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_14 = crag.sum %sum_13, %mode_14_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_15 = crag.sum %sum_14, %mode_15_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_16 = crag.sum %sum_15, %mode_16_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_17 = crag.sum %sum_16, %mode_17_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_18 = crag.sum %sum_17, %mode_18_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_19 = crag.sum %sum_18, %mode_19_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_20 = crag.sum %sum_19, %mode_20_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_21 = crag.sum %sum_20, %mode_21_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_22 = crag.sum %sum_21, %mode_22_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_23 = crag.sum %sum_22, %mode_23_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_24 = crag.sum %sum_23, %mode_24_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_25 = crag.sum %sum_24, %mode_25_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_26 = crag.sum %sum_25, %mode_26_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_27 = crag.sum %sum_26, %mode_27_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_28 = crag.sum %sum_27, %mode_28_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_29 = crag.sum %sum_28, %mode_29_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_30 = crag.sum %sum_29, %mode_30_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_31 = crag.sum %sum_30, %mode_31_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_32 = crag.sum %sum_31, %mode_32_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_33 = crag.sum %sum_32, %mode_33_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_34 = crag.sum %sum_33, %mode_34_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_35 = crag.sum %sum_34, %mode_35_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_36 = crag.sum %sum_35, %mode_36_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_37 = crag.sum %sum_36, %mode_37_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_38 = crag.sum %sum_37, %mode_38_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_39 = crag.sum %sum_38, %mode_39_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_40 = crag.sum %sum_39, %mode_40_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_41 = crag.sum %sum_40, %mode_41_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_42 = crag.sum %sum_41, %mode_42_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>

    // ── Output gain ──────────────────────────────────────────────────────
    %mode_norm = arith.constant 0.023255814 : f32  // 1 / n_modes (43)
    %output_gain_norm = arith.mulf %output_gain, %mode_norm : f32
    %scaled_mono = crag.scale %sum_42, %output_gain_norm : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    crag.output %scaled_mono : !crag.audio<f32, 48000, 1>
  }
}
