// Modal synthesis graph for object 'wooden_block'.
//
// Auto-generated by scripts/modal/codegen/crag_emitter.py from a
// ModeTable produced by the offline FEM extraction pipeline.
// 4 mode(s); sample rate 48000 Hz.
//
// Per-mode IIR design parameters (cutoff, Q) are baked at codegen
// time so the runtime graph has zero per-sample parameter lookups
// inside the resonator inner loop.  The actual
// 2-pole IIR body is built inline by the
// `crag.get_filter_coeffs type = "two_pole_resonator"` lowering.

module {
  crag.graph sample_rate = 48000 channels = 1 {

    // ── Parameters ────────────────────────────────────────────────────────
    %output_gain       = crag.param "output_gain" min = 0.0 max = 4.0 default = 1.0 : f32
    %dampen            = crag.param "dampen" min = 0.0 max = 1.0 default = 0.0 : f32
    %drag_velocity     = crag.param "drag_velocity" min = 0.0 max = 1.0 default = 0.0 : f32
    %drag_roughness    = crag.param "drag_roughness" min = 0.0 max = 1.0 default = 0.5 : f32
    %drag_normal_force = crag.param "drag_normal_force" min = 0.0 max = 1.0 default = 0.5 : f32
    %contact_u         = crag.param "contact_u" min = 0.0 max = 1.0 default = 0.5 : f32
    %contact_v         = crag.param "contact_v" min = 0.0 max = 1.0 default = 0.5 : f32
    %impulse_velocity  = crag.param "impulse_velocity" min = 0.0 max = 1.0 default = 0.5 : f32
    %impulse_angle     = crag.param "impulse_angle" min = 0.0 max = 1.5707963 default = 0.0 unit = "rad" : f32
    %damping_override  = crag.param "damping_override" min = 0.0 max = 1.0 default = 0.0 : f32
    %pitch_shift       = crag.param "pitch_shift" min = 0.5 max = 2.0 default = 1.0 : f32

    // ── Events ────────────────────────────────────────────────────────────
    %impulse_fired, %impulse_at = crag.event_void "impulse" : i1, i32
    %drag_start_fired, %drag_start_at = crag.event_void "drag_start" : i1, i32
    %drag_stop_fired,  %drag_stop_at  = crag.event_void "drag_stop"  : i1, i32

    // ── Impulse excitation: ADSR hammer-hit on `impulse` event ───────────
    %imp_attack_ms = arith.constant 0.1 : f32
    %imp_decay_ms  = arith.constant 1.0 : f32
    %imp_sustain   = arith.constant 0.0 : f32
    %imp_release   = arith.constant 0.0 : f32
    %imp_env = crag.adsr %imp_attack_ms, %imp_decay_ms, %imp_sustain, %imp_release, %impulse_fired, %impulse_at : f32, f32, f32, f32, i1, i32 -> !crag.audio<f32, 48000, 1>
    %impulse_exc = crag.scale %imp_env, %impulse_velocity : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>

    // ── Drag excitation: gated coloured noise ────────────────────────────
    %drag_gate_i1 = crag.latch %drag_start_fired, %drag_stop_fired : i1, i1 -> i1
    %drag_gate_f32 = arith.uitofp %drag_gate_i1 : i1 to f32
    %drag_noise = crag.white_noise : !crag.audio<f32, 48000, 1>
    %drag_cutoff = arith.constant 0.075 : f32
    %drag_fb, %drag_ff = crag.get_filter_coeffs %drag_cutoff order = 2 q = 0.7 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %drag_coloured = crag.filter %drag_noise, %drag_fb, %drag_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %drag_vel_force = arith.mulf %drag_velocity, %drag_normal_force : f32
    %drag_gain = arith.mulf %drag_vel_force, %drag_gate_f32 : f32
    %drag_exc = crag.scale %drag_coloured, %drag_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>

    // ── Excitation mix: impulse + drag → resonator bank input ────────────
    %excitation = crag.sum %impulse_exc, %drag_exc : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>

    // ── Resonator bank (one IIR per surviving mode) ──────────────────────
    %m0_cutoff = arith.constant 0.667930165 : f32
    %m0_gain   = arith.constant 0.457079015 : f32
    %m0_fb, %m0_ff = crag.get_filter_coeffs %m0_cutoff order = 2 q = 19.8371805 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m0_raw = crag.filter %excitation, %m0_fb, %m0_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_0_out = crag.scale %m0_raw, %m0_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m1_cutoff = arith.constant 0.731133873 : f32
    %m1_gain   = arith.constant 2.63338036 : f32
    %m1_fb, %m1_ff = crag.get_filter_coeffs %m1_cutoff order = 2 q = 18.1252852 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m1_raw = crag.filter %excitation, %m1_fb, %m1_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_1_out = crag.scale %m1_raw, %m1_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m2_cutoff = arith.constant 0.777515683 : f32
    %m2_gain   = arith.constant 2.71404403 : f32
    %m2_fb, %m2_ff = crag.get_filter_coeffs %m2_cutoff order = 2 q = 17.0456638 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m2_raw = crag.filter %excitation, %m2_fb, %m2_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_2_out = crag.scale %m2_raw, %m2_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m3_cutoff = arith.constant 0.971829014 : f32
    %m3_gain   = arith.constant 1.15554182 : f32
    %m3_fb, %m3_ff = crag.get_filter_coeffs %m3_cutoff order = 2 q = 13.6410202 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m3_raw = crag.filter %excitation, %m3_fb, %m3_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_3_out = crag.scale %m3_raw, %m3_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>

    // ── Sum the bank ─────────────────────────────────────────────────────
    %sum_1 = crag.sum %mode_0_out, %mode_1_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_2 = crag.sum %sum_1, %mode_2_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_3 = crag.sum %sum_2, %mode_3_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>

    // ── Output gain ──────────────────────────────────────────────────────
    %mode_norm = arith.constant 0.25 : f32  // 1 / n_modes (4)
    %output_gain_norm = arith.mulf %output_gain, %mode_norm : f32
    %scaled_mono = crag.scale %sum_3, %output_gain_norm : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    crag.output %scaled_mono : !crag.audio<f32, 48000, 1>
  }
}
