// Modal synthesis graph for object 'metal_plate'.
//
// Auto-generated by scripts/modal/codegen/crag_emitter.py from a
// ModeTable produced by the offline FEM extraction pipeline.
// 43 mode(s); sample rate 48000 Hz.
//
// Per-mode IIR design parameters (cutoff, Q) are baked at codegen
// time so the runtime graph has zero per-sample parameter lookups
// inside the resonator inner loop (plan §7.3).  The actual
// 2-pole IIR body is built inline by the
// `crag.get_filter_coeffs type = "two_pole_resonator"` lowering.

module {
  crag.graph sample_rate = 48000 channels = 1 {

    // ── Parameters (plan §5.2) ────────────────────────────────────────────
    %output_gain       = crag.param "output_gain" min = 0.0 max = 4.0 default = 1.0 : f32
    %dampen            = crag.param "dampen" min = 0.0 max = 1.0 default = 0.0 : f32
    %drag_velocity     = crag.param "drag_velocity" min = 0.0 max = 1.0 default = 0.0 : f32
    %drag_roughness    = crag.param "drag_roughness" min = 0.0 max = 1.0 default = 0.5 : f32
    %drag_normal_force = crag.param "drag_normal_force" min = 0.0 max = 1.0 default = 0.5 : f32
    %contact_u         = crag.param "contact_u" min = 0.0 max = 1.0 default = 0.5 : f32
    %contact_v         = crag.param "contact_v" min = 0.0 max = 1.0 default = 0.5 : f32
    %impulse_velocity  = crag.param "impulse_velocity" min = 0.0 max = 1.0 default = 0.5 : f32
    %impulse_angle     = crag.param "impulse_angle" min = 0.0 max = 1.5707963 default = 0.0 unit = "rad" : f32
    %damping_override  = crag.param "damping_override" min = 0.0 max = 1.0 default = 0.0 : f32
    %pitch_shift       = crag.param "pitch_shift" min = 0.5 max = 2.0 default = 1.0 : f32

    // ── Events ────────────────────────────────────────────────────────────
    %impulse_fired, %impulse_at = crag.event_void "impulse" : i1, i32
    %drag_start_fired, %drag_start_at = crag.event_void "drag_start" : i1, i32
    %drag_stop_fired,  %drag_stop_at  = crag.event_void "drag_stop"  : i1, i32

    // ── Impulse excitation: ADSR hammer-hit on `impulse` event ───────────
    %imp_attack_ms = arith.constant 0.1 : f32
    %imp_decay_ms  = arith.constant 1.0 : f32
    %imp_sustain   = arith.constant 0.0 : f32
    %imp_release   = arith.constant 0.0 : f32
    %imp_env = crag.adsr %imp_attack_ms, %imp_decay_ms, %imp_sustain, %imp_release, %impulse_fired, %impulse_at : f32, f32, f32, f32, i1, i32 -> !crag.audio<f32, 48000, 1>
    %impulse_exc = crag.scale %imp_env, %impulse_velocity : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>

    // ── Drag excitation: gated coloured noise (plan §3 / §9.4) ───────────
    %drag_gate_i1 = crag.latch %drag_start_fired, %drag_stop_fired : i1, i1 -> i1
    %drag_gate_f32 = arith.uitofp %drag_gate_i1 : i1 to f32
    %drag_noise = crag.white_noise : !crag.audio<f32, 48000, 1>
    %drag_cutoff = arith.constant 0.1875 : f32
    %drag_fb, %drag_ff = crag.get_filter_coeffs %drag_cutoff order = 2 q = 1.1 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %drag_coloured = crag.filter %drag_noise, %drag_fb, %drag_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %drag_vel_force = arith.mulf %drag_velocity, %drag_normal_force : f32
    %drag_gain = arith.mulf %drag_vel_force, %drag_gate_f32 : f32
    %drag_exc = crag.scale %drag_coloured, %drag_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>

    // ── Excitation mix: impulse + drag → resonator bank input ────────────
    %excitation = crag.sum %impulse_exc, %drag_exc : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>

    // ── Dampen runtime-Q shared term (plan §3.3 / §5.1) ─────────────────
    %dampen_two_dz_max = arith.constant 0.2 : f32
    %dampen_x2dz = arith.mulf %dampen, %dampen_two_dz_max : f32

    // ── Resonator bank (one IIR per surviving mode) ──────────────────────
    %m0_cutoff = arith.constant 0.0517170119 : f32
    %m0_gain   = arith.constant 0.913819931 : f32
    %m0_two_zeta_base = arith.constant 0.00136214997 : f32
    %m0_denom = arith.addf %m0_two_zeta_base, %dampen_x2dz : f32
    %m0_one = arith.constant 1.0 : f32
    %m0_q_eff = arith.divf %m0_one, %m0_denom : f32
    %m0_fb, %m0_ff = crag.get_filter_coeffs %m0_cutoff order = 2 q_runtime = %m0_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m0_raw = crag.filter %excitation, %m0_fb, %m0_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_0_out = crag.scale %m0_raw, %m0_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m1_cutoff = arith.constant 0.0785333521 : f32
    %m1_gain   = arith.constant 0.453546942 : f32
    %m1_two_zeta_base = arith.constant 0.00190304448 : f32
    %m1_denom = arith.addf %m1_two_zeta_base, %dampen_x2dz : f32
    %m1_one = arith.constant 1.0 : f32
    %m1_q_eff = arith.divf %m1_one, %m1_denom : f32
    %m1_fb, %m1_ff = crag.get_filter_coeffs %m1_cutoff order = 2 q_runtime = %m1_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m1_raw = crag.filter %excitation, %m1_fb, %m1_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_1_out = crag.scale %m1_raw, %m1_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m2_cutoff = arith.constant 0.125230253 : f32
    %m2_gain   = arith.constant 0.0670371924 : f32
    %m2_two_zeta_base = arith.constant 0.00291207274 : f32
    %m2_denom = arith.addf %m2_two_zeta_base, %dampen_x2dz : f32
    %m2_one = arith.constant 1.0 : f32
    %m2_q_eff = arith.divf %m2_one, %m2_denom : f32
    %m2_fb, %m2_ff = crag.get_filter_coeffs %m2_cutoff order = 2 q_runtime = %m2_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m2_raw = crag.filter %excitation, %m2_fb, %m2_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_2_out = crag.scale %m2_raw, %m2_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m3_cutoff = arith.constant 0.146679203 : f32
    %m3_gain   = arith.constant 0.925735052 : f32
    %m3_two_zeta_base = arith.constant 0.00338562133 : f32
    %m3_denom = arith.addf %m3_two_zeta_base, %dampen_x2dz : f32
    %m3_one = arith.constant 1.0 : f32
    %m3_q_eff = arith.divf %m3_one, %m3_denom : f32
    %m3_fb, %m3_ff = crag.get_filter_coeffs %m3_cutoff order = 2 q_runtime = %m3_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m3_raw = crag.filter %excitation, %m3_fb, %m3_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_3_out = crag.scale %m3_raw, %m3_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m4_cutoff = arith.constant 0.180717533 : f32
    %m4_gain   = arith.constant 0.129164368 : f32
    %m4_two_zeta_base = arith.constant 0.00414277701 : f32
    %m4_denom = arith.addf %m4_two_zeta_base, %dampen_x2dz : f32
    %m4_one = arith.constant 1.0 : f32
    %m4_q_eff = arith.divf %m4_one, %m4_denom : f32
    %m4_fb, %m4_ff = crag.get_filter_coeffs %m4_cutoff order = 2 q_runtime = %m4_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m4_raw = crag.filter %excitation, %m4_fb, %m4_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_4_out = crag.scale %m4_raw, %m4_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m5_cutoff = arith.constant 0.216245851 : f32
    %m5_gain   = arith.constant 0.130387542 : f32
    %m5_two_zeta_base = arith.constant 0.00493736533 : f32
    %m5_denom = arith.addf %m5_two_zeta_base, %dampen_x2dz : f32
    %m5_one = arith.constant 1.0 : f32
    %m5_q_eff = arith.divf %m5_one, %m5_denom : f32
    %m5_fb, %m5_ff = crag.get_filter_coeffs %m5_cutoff order = 2 q_runtime = %m5_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m5_raw = crag.filter %excitation, %m5_fb, %m5_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_5_out = crag.scale %m5_raw, %m5_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m6_cutoff = arith.constant 0.226883997 : f32
    %m6_gain   = arith.constant 1.23677123 : f32
    %m6_two_zeta_base = arith.constant 0.0051758377 : f32
    %m6_denom = arith.addf %m6_two_zeta_base, %dampen_x2dz : f32
    %m6_one = arith.constant 1.0 : f32
    %m6_q_eff = arith.divf %m6_one, %m6_denom : f32
    %m6_fb, %m6_ff = crag.get_filter_coeffs %m6_cutoff order = 2 q_runtime = %m6_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m6_raw = crag.filter %excitation, %m6_fb, %m6_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_6_out = crag.scale %m6_raw, %m6_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m7_cutoff = arith.constant 0.266917588 : f32
    %m7_gain   = arith.constant 0.877883471 : f32
    %m7_two_zeta_base = arith.constant 0.00607480047 : f32
    %m7_denom = arith.addf %m7_two_zeta_base, %dampen_x2dz : f32
    %m7_one = arith.constant 1.0 : f32
    %m7_q_eff = arith.divf %m7_one, %m7_denom : f32
    %m7_fb, %m7_ff = crag.get_filter_coeffs %m7_cutoff order = 2 q_runtime = %m7_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m7_raw = crag.filter %excitation, %m7_fb, %m7_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_7_out = crag.scale %m7_raw, %m7_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m8_cutoff = arith.constant 0.313464533 : f32
    %m8_gain   = arith.constant 0.455274544 : f32
    %m8_two_zeta_base = arith.constant 0.00712213373 : f32
    %m8_denom = arith.addf %m8_two_zeta_base, %dampen_x2dz : f32
    %m8_one = arith.constant 1.0 : f32
    %m8_q_eff = arith.divf %m8_one, %m8_denom : f32
    %m8_fb, %m8_ff = crag.get_filter_coeffs %m8_cutoff order = 2 q_runtime = %m8_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m8_raw = crag.filter %excitation, %m8_fb, %m8_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_8_out = crag.scale %m8_raw, %m8_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m9_cutoff = arith.constant 0.342296279 : f32
    %m9_gain   = arith.constant 0.0827614657 : f32
    %m9_two_zeta_base = arith.constant 0.00777161959 : f32
    %m9_denom = arith.addf %m9_two_zeta_base, %dampen_x2dz : f32
    %m9_one = arith.constant 1.0 : f32
    %m9_q_eff = arith.divf %m9_one, %m9_denom : f32
    %m9_fb, %m9_ff = crag.get_filter_coeffs %m9_cutoff order = 2 q_runtime = %m9_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m9_raw = crag.filter %excitation, %m9_fb, %m9_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_9_out = crag.scale %m9_raw, %m9_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m10_cutoff = arith.constant 0.344346428 : f32
    %m10_gain   = arith.constant 0.0663816049 : f32
    %m10_two_zeta_base = arith.constant 0.00781781984 : f32
    %m10_denom = arith.addf %m10_two_zeta_base, %dampen_x2dz : f32
    %m10_one = arith.constant 1.0 : f32
    %m10_q_eff = arith.divf %m10_one, %m10_denom : f32
    %m10_fb, %m10_ff = crag.get_filter_coeffs %m10_cutoff order = 2 q_runtime = %m10_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m10_raw = crag.filter %excitation, %m10_fb, %m10_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_10_out = crag.scale %m10_raw, %m10_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m11_cutoff = arith.constant 0.354005062 : f32
    %m11_gain   = arith.constant 0.173046472 : f32
    %m11_two_zeta_base = arith.constant 0.00803550484 : f32
    %m11_denom = arith.addf %m11_two_zeta_base, %dampen_x2dz : f32
    %m11_one = arith.constant 1.0 : f32
    %m11_q_eff = arith.divf %m11_one, %m11_denom : f32
    %m11_fb, %m11_ff = crag.get_filter_coeffs %m11_cutoff order = 2 q_runtime = %m11_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m11_raw = crag.filter %excitation, %m11_fb, %m11_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_11_out = crag.scale %m11_raw, %m11_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m12_cutoff = arith.constant 0.362333062 : f32
    %m12_gain   = arith.constant 1.18629636 : f32
    %m12_two_zeta_base = arith.constant 0.00822323392 : f32
    %m12_denom = arith.addf %m12_two_zeta_base, %dampen_x2dz : f32
    %m12_one = arith.constant 1.0 : f32
    %m12_q_eff = arith.divf %m12_one, %m12_denom : f32
    %m12_fb, %m12_ff = crag.get_filter_coeffs %m12_cutoff order = 2 q_runtime = %m12_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m12_raw = crag.filter %excitation, %m12_fb, %m12_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_12_out = crag.scale %m12_raw, %m12_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m13_cutoff = arith.constant 0.400164057 : f32
    %m13_gain   = arith.constant 0.178196401 : f32
    %m13_two_zeta_base = arith.constant 0.00907635549 : f32
    %m13_denom = arith.addf %m13_two_zeta_base, %dampen_x2dz : f32
    %m13_one = arith.constant 1.0 : f32
    %m13_q_eff = arith.divf %m13_one, %m13_denom : f32
    %m13_fb, %m13_ff = crag.get_filter_coeffs %m13_cutoff order = 2 q_runtime = %m13_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m13_raw = crag.filter %excitation, %m13_fb, %m13_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_13_out = crag.scale %m13_raw, %m13_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m14_cutoff = arith.constant 0.454094499 : f32
    %m14_gain   = arith.constant 0.930928477 : f32
    %m14_two_zeta_base = arith.constant 0.0102932811 : f32
    %m14_denom = arith.addf %m14_two_zeta_base, %dampen_x2dz : f32
    %m14_one = arith.constant 1.0 : f32
    %m14_q_eff = arith.divf %m14_one, %m14_denom : f32
    %m14_fb, %m14_ff = crag.get_filter_coeffs %m14_cutoff order = 2 q_runtime = %m14_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m14_raw = crag.filter %excitation, %m14_fb, %m14_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_14_out = crag.scale %m14_raw, %m14_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m15_cutoff = arith.constant 0.473423864 : f32
    %m15_gain   = arith.constant 0.149062505 : f32
    %m15_two_zeta_base = arith.constant 0.0107296067 : f32
    %m15_denom = arith.addf %m15_two_zeta_base, %dampen_x2dz : f32
    %m15_one = arith.constant 1.0 : f32
    %m15_q_eff = arith.divf %m15_one, %m15_denom : f32
    %m15_fb, %m15_ff = crag.get_filter_coeffs %m15_cutoff order = 2 q_runtime = %m15_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m15_raw = crag.filter %excitation, %m15_fb, %m15_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_15_out = crag.scale %m15_raw, %m15_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m16_cutoff = arith.constant 0.479901843 : f32
    %m16_gain   = arith.constant 0.826629636 : f32
    %m16_two_zeta_base = arith.constant 0.0108758515 : f32
    %m16_denom = arith.addf %m16_two_zeta_base, %dampen_x2dz : f32
    %m16_one = arith.constant 1.0 : f32
    %m16_q_eff = arith.divf %m16_one, %m16_denom : f32
    %m16_fb, %m16_ff = crag.get_filter_coeffs %m16_cutoff order = 2 q_runtime = %m16_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m16_raw = crag.filter %excitation, %m16_fb, %m16_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_16_out = crag.scale %m16_raw, %m16_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m17_cutoff = arith.constant 0.498780292 : f32
    %m17_gain   = arith.constant 0.0722401134 : f32
    %m17_two_zeta_base = arith.constant 0.0113020874 : f32
    %m17_denom = arith.addf %m17_two_zeta_base, %dampen_x2dz : f32
    %m17_one = arith.constant 1.0 : f32
    %m17_q_eff = arith.divf %m17_one, %m17_denom : f32
    %m17_fb, %m17_ff = crag.get_filter_coeffs %m17_cutoff order = 2 q_runtime = %m17_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m17_raw = crag.filter %excitation, %m17_fb, %m17_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_17_out = crag.scale %m17_raw, %m17_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m18_cutoff = arith.constant 0.527873485 : f32
    %m18_gain   = arith.constant 1.32713 : f32
    %m18_two_zeta_base = arith.constant 0.0119590608 : f32
    %m18_denom = arith.addf %m18_two_zeta_base, %dampen_x2dz : f32
    %m18_one = arith.constant 1.0 : f32
    %m18_q_eff = arith.divf %m18_one, %m18_denom : f32
    %m18_fb, %m18_ff = crag.get_filter_coeffs %m18_cutoff order = 2 q_runtime = %m18_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m18_raw = crag.filter %excitation, %m18_fb, %m18_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_18_out = crag.scale %m18_raw, %m18_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m19_cutoff = arith.constant 0.530532928 : f32
    %m19_gain   = arith.constant 0.712969819 : f32
    %m19_two_zeta_base = arith.constant 0.0120191215 : f32
    %m19_denom = arith.addf %m19_two_zeta_base, %dampen_x2dz : f32
    %m19_one = arith.constant 1.0 : f32
    %m19_q_eff = arith.divf %m19_one, %m19_denom : f32
    %m19_fb, %m19_ff = crag.get_filter_coeffs %m19_cutoff order = 2 q_runtime = %m19_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m19_raw = crag.filter %excitation, %m19_fb, %m19_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_19_out = crag.scale %m19_raw, %m19_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m20_cutoff = arith.constant 0.556878695 : f32
    %m20_gain   = arith.constant 0.0639645832 : f32
    %m20_two_zeta_base = arith.constant 0.0126141617 : f32
    %m20_denom = arith.addf %m20_two_zeta_base, %dampen_x2dz : f32
    %m20_one = arith.constant 1.0 : f32
    %m20_q_eff = arith.divf %m20_one, %m20_denom : f32
    %m20_fb, %m20_ff = crag.get_filter_coeffs %m20_cutoff order = 2 q_runtime = %m20_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m20_raw = crag.filter %excitation, %m20_fb, %m20_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_20_out = crag.scale %m20_raw, %m20_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m21_cutoff = arith.constant 0.560593893 : f32
    %m21_gain   = arith.constant 0.0792287548 : f32
    %m21_two_zeta_base = arith.constant 0.0126980791 : f32
    %m21_denom = arith.addf %m21_two_zeta_base, %dampen_x2dz : f32
    %m21_one = arith.constant 1.0 : f32
    %m21_q_eff = arith.divf %m21_one, %m21_denom : f32
    %m21_fb, %m21_ff = crag.get_filter_coeffs %m21_cutoff order = 2 q_runtime = %m21_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m21_raw = crag.filter %excitation, %m21_fb, %m21_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_21_out = crag.scale %m21_raw, %m21_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m22_cutoff = arith.constant 0.569565516 : f32
    %m22_gain   = arith.constant 0.139559007 : f32
    %m22_two_zeta_base = arith.constant 0.012900733 : f32
    %m22_denom = arith.addf %m22_two_zeta_base, %dampen_x2dz : f32
    %m22_one = arith.constant 1.0 : f32
    %m22_q_eff = arith.divf %m22_one, %m22_denom : f32
    %m22_fb, %m22_ff = crag.get_filter_coeffs %m22_cutoff order = 2 q_runtime = %m22_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m22_raw = crag.filter %excitation, %m22_fb, %m22_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_22_out = crag.scale %m22_raw, %m22_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m23_cutoff = arith.constant 0.58354487 : f32
    %m23_gain   = arith.constant 0.405211597 : f32
    %m23_two_zeta_base = arith.constant 0.0132165201 : f32
    %m23_denom = arith.addf %m23_two_zeta_base, %dampen_x2dz : f32
    %m23_one = arith.constant 1.0 : f32
    %m23_q_eff = arith.divf %m23_one, %m23_denom : f32
    %m23_fb, %m23_ff = crag.get_filter_coeffs %m23_cutoff order = 2 q_runtime = %m23_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m23_raw = crag.filter %excitation, %m23_fb, %m23_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_23_out = crag.scale %m23_raw, %m23_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m24_cutoff = arith.constant 0.613213584 : f32
    %m24_gain   = arith.constant 0.375470863 : f32
    %m24_two_zeta_base = arith.constant 0.0138867859 : f32
    %m24_denom = arith.addf %m24_two_zeta_base, %dampen_x2dz : f32
    %m24_one = arith.constant 1.0 : f32
    %m24_q_eff = arith.divf %m24_one, %m24_denom : f32
    %m24_fb, %m24_ff = crag.get_filter_coeffs %m24_cutoff order = 2 q_runtime = %m24_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m24_raw = crag.filter %excitation, %m24_fb, %m24_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_24_out = crag.scale %m24_raw, %m24_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m25_cutoff = arith.constant 0.653684487 : f32
    %m25_gain   = arith.constant 0.297732933 : f32
    %m25_two_zeta_base = arith.constant 0.0148012119 : f32
    %m25_denom = arith.addf %m25_two_zeta_base, %dampen_x2dz : f32
    %m25_one = arith.constant 1.0 : f32
    %m25_q_eff = arith.divf %m25_one, %m25_denom : f32
    %m25_fb, %m25_ff = crag.get_filter_coeffs %m25_cutoff order = 2 q_runtime = %m25_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m25_raw = crag.filter %excitation, %m25_fb, %m25_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_25_out = crag.scale %m25_raw, %m25_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m26_cutoff = arith.constant 0.719094229 : f32
    %m26_gain   = arith.constant 0.231485814 : f32
    %m26_two_zeta_base = arith.constant 0.0162793612 : f32
    %m26_denom = arith.addf %m26_two_zeta_base, %dampen_x2dz : f32
    %m26_one = arith.constant 1.0 : f32
    %m26_q_eff = arith.divf %m26_one, %m26_denom : f32
    %m26_fb, %m26_ff = crag.get_filter_coeffs %m26_cutoff order = 2 q_runtime = %m26_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m26_raw = crag.filter %excitation, %m26_fb, %m26_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_26_out = crag.scale %m26_raw, %m26_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m27_cutoff = arith.constant 0.735475675 : f32
    %m27_gain   = arith.constant 0.866848105 : f32
    %m27_two_zeta_base = arith.constant 0.0166495927 : f32
    %m27_denom = arith.addf %m27_two_zeta_base, %dampen_x2dz : f32
    %m27_one = arith.constant 1.0 : f32
    %m27_q_eff = arith.divf %m27_one, %m27_denom : f32
    %m27_fb, %m27_ff = crag.get_filter_coeffs %m27_cutoff order = 2 q_runtime = %m27_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m27_raw = crag.filter %excitation, %m27_fb, %m27_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_27_out = crag.scale %m27_raw, %m27_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m28_cutoff = arith.constant 0.759048079 : f32
    %m28_gain   = arith.constant 0.306435623 : f32
    %m28_two_zeta_base = arith.constant 0.0171823679 : f32
    %m28_denom = arith.addf %m28_two_zeta_base, %dampen_x2dz : f32
    %m28_one = arith.constant 1.0 : f32
    %m28_q_eff = arith.divf %m28_one, %m28_denom : f32
    %m28_fb, %m28_ff = crag.get_filter_coeffs %m28_cutoff order = 2 q_runtime = %m28_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m28_raw = crag.filter %excitation, %m28_fb, %m28_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_28_out = crag.scale %m28_raw, %m28_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m29_cutoff = arith.constant 0.760888002 : f32
    %m29_gain   = arith.constant 0.078352604 : f32
    %m29_two_zeta_base = arith.constant 0.0172239543 : f32
    %m29_denom = arith.addf %m29_two_zeta_base, %dampen_x2dz : f32
    %m29_one = arith.constant 1.0 : f32
    %m29_q_eff = arith.divf %m29_one, %m29_denom : f32
    %m29_fb, %m29_ff = crag.get_filter_coeffs %m29_cutoff order = 2 q_runtime = %m29_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m29_raw = crag.filter %excitation, %m29_fb, %m29_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_29_out = crag.scale %m29_raw, %m29_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m30_cutoff = arith.constant 0.77283668 : f32
    %m30_gain   = arith.constant 1.66191406 : f32
    %m30_two_zeta_base = arith.constant 0.0174940249 : f32
    %m30_denom = arith.addf %m30_two_zeta_base, %dampen_x2dz : f32
    %m30_one = arith.constant 1.0 : f32
    %m30_q_eff = arith.divf %m30_one, %m30_denom : f32
    %m30_fb, %m30_ff = crag.get_filter_coeffs %m30_cutoff order = 2 q_runtime = %m30_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m30_raw = crag.filter %excitation, %m30_fb, %m30_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_30_out = crag.scale %m30_raw, %m30_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m31_cutoff = arith.constant 0.791361033 : f32
    %m31_gain   = arith.constant 0.0952678216 : f32
    %m31_two_zeta_base = arith.constant 0.0179127346 : f32
    %m31_denom = arith.addf %m31_two_zeta_base, %dampen_x2dz : f32
    %m31_one = arith.constant 1.0 : f32
    %m31_q_eff = arith.divf %m31_one, %m31_denom : f32
    %m31_fb, %m31_ff = crag.get_filter_coeffs %m31_cutoff order = 2 q_runtime = %m31_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m31_raw = crag.filter %excitation, %m31_fb, %m31_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_31_out = crag.scale %m31_raw, %m31_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m32_cutoff = arith.constant 0.803304996 : f32
    %m32_gain   = arith.constant 1.3520109 : f32
    %m32_two_zeta_base = arith.constant 0.0181827138 : f32
    %m32_denom = arith.addf %m32_two_zeta_base, %dampen_x2dz : f32
    %m32_one = arith.constant 1.0 : f32
    %m32_q_eff = arith.divf %m32_one, %m32_denom : f32
    %m32_fb, %m32_ff = crag.get_filter_coeffs %m32_cutoff order = 2 q_runtime = %m32_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m32_raw = crag.filter %excitation, %m32_fb, %m32_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_32_out = crag.scale %m32_raw, %m32_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m33_cutoff = arith.constant 0.808533915 : f32
    %m33_gain   = arith.constant 1.17610111 : f32
    %m33_two_zeta_base = arith.constant 0.018300909 : f32
    %m33_denom = arith.addf %m33_two_zeta_base, %dampen_x2dz : f32
    %m33_one = arith.constant 1.0 : f32
    %m33_q_eff = arith.divf %m33_one, %m33_denom : f32
    %m33_fb, %m33_ff = crag.get_filter_coeffs %m33_cutoff order = 2 q_runtime = %m33_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m33_raw = crag.filter %excitation, %m33_fb, %m33_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_33_out = crag.scale %m33_raw, %m33_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m34_cutoff = arith.constant 0.808840686 : f32
    %m34_gain   = arith.constant 0.223667439 : f32
    %m34_two_zeta_base = arith.constant 0.0183078434 : f32
    %m34_denom = arith.addf %m34_two_zeta_base, %dampen_x2dz : f32
    %m34_one = arith.constant 1.0 : f32
    %m34_q_eff = arith.divf %m34_one, %m34_denom : f32
    %m34_fb, %m34_ff = crag.get_filter_coeffs %m34_cutoff order = 2 q_runtime = %m34_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m34_raw = crag.filter %excitation, %m34_fb, %m34_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_34_out = crag.scale %m34_raw, %m34_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m35_cutoff = arith.constant 0.860995945 : f32
    %m35_gain   = arith.constant 0.451823939 : f32
    %m35_two_zeta_base = arith.constant 0.0194868226 : f32
    %m35_denom = arith.addf %m35_two_zeta_base, %dampen_x2dz : f32
    %m35_one = arith.constant 1.0 : f32
    %m35_q_eff = arith.divf %m35_one, %m35_denom : f32
    %m35_fb, %m35_ff = crag.get_filter_coeffs %m35_cutoff order = 2 q_runtime = %m35_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m35_raw = crag.filter %excitation, %m35_fb, %m35_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_35_out = crag.scale %m35_raw, %m35_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m36_cutoff = arith.constant 0.888528239 : f32
    %m36_gain   = arith.constant 0.14834511 : f32
    %m36_two_zeta_base = arith.constant 0.0201092304 : f32
    %m36_denom = arith.addf %m36_two_zeta_base, %dampen_x2dz : f32
    %m36_one = arith.constant 1.0 : f32
    %m36_q_eff = arith.divf %m36_one, %m36_denom : f32
    %m36_fb, %m36_ff = crag.get_filter_coeffs %m36_cutoff order = 2 q_runtime = %m36_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m36_raw = crag.filter %excitation, %m36_fb, %m36_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_36_out = crag.scale %m36_raw, %m36_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m37_cutoff = arith.constant 0.930900067 : f32
    %m37_gain   = arith.constant 0.489666999 : f32
    %m37_two_zeta_base = arith.constant 0.021067149 : f32
    %m37_denom = arith.addf %m37_two_zeta_base, %dampen_x2dz : f32
    %m37_one = arith.constant 1.0 : f32
    %m37_q_eff = arith.divf %m37_one, %m37_denom : f32
    %m37_fb, %m37_ff = crag.get_filter_coeffs %m37_cutoff order = 2 q_runtime = %m37_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m37_raw = crag.filter %excitation, %m37_fb, %m37_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_37_out = crag.scale %m37_raw, %m37_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m38_cutoff = arith.constant 0.931880655 : f32
    %m38_gain   = arith.constant 0.156278594 : f32
    %m38_two_zeta_base = arith.constant 0.0210893181 : f32
    %m38_denom = arith.addf %m38_two_zeta_base, %dampen_x2dz : f32
    %m38_one = arith.constant 1.0 : f32
    %m38_q_eff = arith.divf %m38_one, %m38_denom : f32
    %m38_fb, %m38_ff = crag.get_filter_coeffs %m38_cutoff order = 2 q_runtime = %m38_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m38_raw = crag.filter %excitation, %m38_fb, %m38_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_38_out = crag.scale %m38_raw, %m38_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m39_cutoff = arith.constant 0.972614649 : f32
    %m39_gain   = arith.constant 0.0724255407 : f32
    %m39_two_zeta_base = arith.constant 0.0220102523 : f32
    %m39_denom = arith.addf %m39_two_zeta_base, %dampen_x2dz : f32
    %m39_one = arith.constant 1.0 : f32
    %m39_q_eff = arith.divf %m39_one, %m39_denom : f32
    %m39_fb, %m39_ff = crag.get_filter_coeffs %m39_cutoff order = 2 q_runtime = %m39_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m39_raw = crag.filter %excitation, %m39_fb, %m39_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_39_out = crag.scale %m39_raw, %m39_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m40_cutoff = arith.constant 0.973141698 : f32
    %m40_gain   = arith.constant 0.669069813 : f32
    %m40_two_zeta_base = arith.constant 0.0220221683 : f32
    %m40_denom = arith.addf %m40_two_zeta_base, %dampen_x2dz : f32
    %m40_one = arith.constant 1.0 : f32
    %m40_q_eff = arith.divf %m40_one, %m40_denom : f32
    %m40_fb, %m40_ff = crag.get_filter_coeffs %m40_cutoff order = 2 q_runtime = %m40_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m40_raw = crag.filter %excitation, %m40_fb, %m40_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_40_out = crag.scale %m40_raw, %m40_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m41_cutoff = arith.constant 0.978872171 : f32
    %m41_gain   = arith.constant 2.55329027 : f32
    %m41_two_zeta_base = arith.constant 0.0221517288 : f32
    %m41_denom = arith.addf %m41_two_zeta_base, %dampen_x2dz : f32
    %m41_one = arith.constant 1.0 : f32
    %m41_q_eff = arith.divf %m41_one, %m41_denom : f32
    %m41_fb, %m41_ff = crag.get_filter_coeffs %m41_cutoff order = 2 q_runtime = %m41_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m41_raw = crag.filter %excitation, %m41_fb, %m41_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_41_out = crag.scale %m41_raw, %m41_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    %m42_cutoff = arith.constant 0.99206011 : f32
    %m42_gain   = arith.constant 0.0932069749 : f32
    %m42_two_zeta_base = arith.constant 0.0224498978 : f32
    %m42_denom = arith.addf %m42_two_zeta_base, %dampen_x2dz : f32
    %m42_one = arith.constant 1.0 : f32
    %m42_q_eff = arith.divf %m42_one, %m42_denom : f32
    %m42_fb, %m42_ff = crag.get_filter_coeffs %m42_cutoff order = 2 q_runtime = %m42_q_eff : f32 type = "two_pole_resonator" : f32, !crag.coeff_vec, !crag.coeff_vec
    %m42_raw = crag.filter %excitation, %m42_fb, %m42_ff : (!crag.audio<f32, 48000, 1>, !crag.coeff_vec, !crag.coeff_vec) -> !crag.audio<f32, 48000, 1>
    %mode_42_out = crag.scale %m42_raw, %m42_gain : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>

    // ── Sum the bank ─────────────────────────────────────────────────────
    %sum_1 = crag.sum %mode_0_out, %mode_1_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_2 = crag.sum %sum_1, %mode_2_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_3 = crag.sum %sum_2, %mode_3_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_4 = crag.sum %sum_3, %mode_4_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_5 = crag.sum %sum_4, %mode_5_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_6 = crag.sum %sum_5, %mode_6_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_7 = crag.sum %sum_6, %mode_7_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_8 = crag.sum %sum_7, %mode_8_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_9 = crag.sum %sum_8, %mode_9_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_10 = crag.sum %sum_9, %mode_10_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_11 = crag.sum %sum_10, %mode_11_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_12 = crag.sum %sum_11, %mode_12_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_13 = crag.sum %sum_12, %mode_13_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_14 = crag.sum %sum_13, %mode_14_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_15 = crag.sum %sum_14, %mode_15_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_16 = crag.sum %sum_15, %mode_16_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_17 = crag.sum %sum_16, %mode_17_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_18 = crag.sum %sum_17, %mode_18_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_19 = crag.sum %sum_18, %mode_19_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_20 = crag.sum %sum_19, %mode_20_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_21 = crag.sum %sum_20, %mode_21_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_22 = crag.sum %sum_21, %mode_22_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_23 = crag.sum %sum_22, %mode_23_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_24 = crag.sum %sum_23, %mode_24_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_25 = crag.sum %sum_24, %mode_25_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_26 = crag.sum %sum_25, %mode_26_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_27 = crag.sum %sum_26, %mode_27_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_28 = crag.sum %sum_27, %mode_28_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_29 = crag.sum %sum_28, %mode_29_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_30 = crag.sum %sum_29, %mode_30_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_31 = crag.sum %sum_30, %mode_31_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_32 = crag.sum %sum_31, %mode_32_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_33 = crag.sum %sum_32, %mode_33_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_34 = crag.sum %sum_33, %mode_34_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_35 = crag.sum %sum_34, %mode_35_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_36 = crag.sum %sum_35, %mode_36_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_37 = crag.sum %sum_36, %mode_37_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_38 = crag.sum %sum_37, %mode_38_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_39 = crag.sum %sum_38, %mode_39_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_40 = crag.sum %sum_39, %mode_40_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_41 = crag.sum %sum_40, %mode_41_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>
    %sum_42 = crag.sum %sum_41, %mode_42_out : (!crag.audio<f32, 48000, 1>, !crag.audio<f32, 48000, 1>) -> !crag.audio<f32, 48000, 1>

    // ── Output gain ──────────────────────────────────────────────────────
    %mode_norm = arith.constant 0.023255814 : f32  // 1 / n_modes (43)
    %output_gain_norm = arith.mulf %output_gain, %mode_norm : f32
    %scaled_mono = crag.scale %sum_42, %output_gain_norm : !crag.audio<f32, 48000, 1>, f32 -> !crag.audio<f32, 48000, 1>
    crag.output %scaled_mono : !crag.audio<f32, 48000, 1>
  }
}
